-- ============================================================================
-- Seed: register the synthetic Medicare final-rule TEST PDF as an ingestion
-- source so the platform's extraction engine runs on it end-to-end.
--
-- Prereq: the PDF must already be generated + served, i.e.
--   node scripts/gen-medicare-test-pdf.mjs      (writes public/test-fixtures/…)
--   rebuild/restart so Next serves public/, then it's reachable at
--   https://app.pallio.io/test-fixtures/medicare-final-rule-2026.pdf
--
-- Why payer_id + state are REQUIRED here:
--   ingestDocumentFromUrl only writes payer_rule rows when BOTH payer_id and
--   state are set (document-ingestion.service.ts ~L185). CMS-wide sources can
--   leave them NULL, but then extraction embeds only — no structured rules to
--   compare. For this test we bind Medicare + OH so rules actually persist.
--
-- document_type = 'cms_pfs'  →  confidence band 0.95 (CMS Physician Fee
-- Schedule / final rule), created_by = 'crawler:cms_pfs' on every rule.
--
-- Idempotent: ON CONFLICT (url) DO UPDATE re-points metadata AND resets the
-- fetch bookkeeping so the very next cron tick re-fetches + re-extracts (handy
-- when you regenerate the PDF with different scenarios).
--
-- Apply on the VPS:
--   sudo -u postgres psql pallio -f db/seed/ingestion-source-medicare-pdf.sql
-- Then fire the cron once (extracts):
--   curl -X POST -H "x-cron-secret: $CRON_SECRET" \
--        https://app.pallio.io/api/cron/ingest-documents
-- Verify the source ran clean + rules landed:
--   sudo -u postgres psql pallio -c \
--     "SELECT name,last_check_at,last_ingested_at,last_error FROM ingestion_source WHERE url LIKE '%medicare-final-rule-2026%';"
--   sudo -u postgres psql pallio -c \
--     "SELECT code,attribute,coverage_status,confidence FROM payer_rule WHERE created_by='crawler:cms_pfs' AND expiration_date IS NULL ORDER BY code;"
-- ============================================================================

WITH medicare AS (
  SELECT id FROM payer
   WHERE name ILIKE '%medicare%'
   ORDER BY (payer_type = 'medicare_mac') DESC, created_at ASC
   LIMIT 1
)
INSERT INTO ingestion_source (name, url, payer_id, state, document_type, schedule_cadence, notes)
VALUES (
  'TEST — Medicare Final Rule (home-based & palliative, CY2026)',
  'https://app.pallio.io/test-fixtures/medicare-final-rule-2026.pdf',
  (SELECT id FROM medicare),
  'OH',
  'cms_pfs',
  'monthly',
  'Synthetic extraction/comparison test fixture. 12 varied scenarios: covered, not_covered, prior_auth, telehealth, frequency_limit, documentation, addon. Generated by scripts/gen-medicare-test-pdf.mjs.'
)
ON CONFLICT (url) DO UPDATE SET
  name              = EXCLUDED.name,
  payer_id          = EXCLUDED.payer_id,
  state             = EXCLUDED.state,
  document_type     = EXCLUDED.document_type,
  schedule_cadence  = EXCLUDED.schedule_cadence,
  notes             = EXCLUDED.notes,
  -- reset bookkeeping so the next cron tick re-fetches + re-extracts
  last_content_hash = NULL,
  last_check_at     = NULL,
  last_error        = NULL,
  active            = TRUE,
  updated_at        = now();

-- Show what we just registered (and confirm Medicare resolved).
SELECT s.name, s.url, s.payer_id, p.name AS payer, s.state, s.document_type, s.active
  FROM ingestion_source s
  LEFT JOIN payer p ON p.id = s.payer_id
 WHERE s.url LIKE '%medicare-final-rule-2026%';
