-- ============================================================================
-- payer-rules-aetna-frequency.sql
--
-- Aetna's frequency position on all 25 in-scope codes: there is no published
-- per-code limit, and the benefit plan is where any limit lives.
--
-- WHY THIS EXISTS
-- One hand-typed rule used to sit on 99350 frequency_limit. It was withdrawn
-- with the other six typed rules, because a payer rule somebody composed is
-- not citable however well formed it is. That left the attribute empty for
-- every Aetna code, and every deploy since has printed
--   "now unanswered: Aetna 99350 frequency_limit"
-- which is honest but not an answer.
--
-- The temptation is to invent the number. What Aetna actually publishes is
-- the sentence these rules cite:
--
--   "Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits."
--
-- That is a real determination and it is worth recording: a biller asking
-- "how many visits can I bill?" learns that Aetna sets no published per-code
-- cap, that a cap may still exist in the member's plan, and where to look.
-- coverage_status is 'unknown' rather than 'covered' precisely because a limit
-- may exist — absence of a published limit is not permission.
--
-- WHAT THIS DELIBERATELY DOES NOT DO
-- It does not carry maxOccurrences or windowDays. db/maintenance/backfill-
-- structured-scorer-fields.sql fills those for rules that state a real cap,
-- and the denial scorer reads them; a fabricated cap here would feed a
-- fabricated denial prediction. No cap is published, so no cap is recorded.
-- ============================================================================

BEGIN;

UPDATE payer_rule pr
   SET expiration_date = GREATEST(pr.effective_date, DATE '2026-01-01')
 WHERE pr.expiration_date IS NULL
   AND pr.created_by <> 'extract:aetna-frequency-basis-2026-08'
   AND pr.payer_id = 'a0000000-0000-4000-8000-000000000301'::uuid
   AND pr.attribute = 'frequency_limit';

INSERT INTO payer_rule (id, payer_id, state, product_line, code, attribute, value, coverage_status, confidence, effective_date, expiration_date, source_doc_id, source_quote, created_by)
VALUES
  ('8d0f3bab-909f-4bec-8cda-2f76e9fcca8e'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99341', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99341. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('2d550c8b-13a6-4960-8bba-2767dbd38c4f'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99342', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99342. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('de5ba539-430e-4194-8f14-892469399704'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99344', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99344. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('129204a7-9b48-455f-8926-3b77b559df32'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99345', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99345. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('4cbf2361-a993-4ec0-8557-3c991492c428'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99347', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99347. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('bbb50e0d-ca30-4ead-84c3-573c81587fef'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99348', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99348. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('2b1dc791-48f3-4535-86fe-7d59856bfdb9'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99349', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99349. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('673c5d4c-e9ac-48f8-8f19-44be1aae938b'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99350', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99350. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('95bee2e7-8698-40e8-8775-c531e838cc37'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99417', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99417. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('5bde8fea-e6a2-4d2e-840f-5282cb8a34a2'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99424', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99424. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('9998eb37-bbdb-4505-8cdc-cd11769bdc1e'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99425', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99425. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('1e73f09d-1226-4d55-8913-8108f213f56c'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99426', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99426. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('938c57d7-513a-45c0-878d-3c7ad710f10c'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99427', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99427. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('95e957b1-e3a7-413c-834f-7a1bf94f69a6'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99439', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99439. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('de02d597-5a45-4c29-8797-1398a6ab2052'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99490', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99490. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('9066cecd-b7e7-469a-834c-540fca0af8d7'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99491', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99491. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('d5aca87b-45bb-45c9-8546-112066205dec'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99495', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99495. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('24694e3e-f780-4be1-8091-1e846f6b04fb'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99496', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99496. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('6a58ef26-7a30-43e9-8d03-0fb13a990fbd'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99497', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99497. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('3db02a25-239f-4389-8058-3bc02fa98880'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99498', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99498. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('c2f04852-46f0-4d55-8b29-3d7a95b4cce2'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', '99499', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for 99499. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('a86f7be7-3c44-448e-85b6-982a6312385c'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', 'G0179', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for G0179. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('1dc11fcd-68ba-4af8-8432-a527985f6ec6'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', 'G0180', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for G0180. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('80b81bc3-9e77-4eb3-8753-f0355ada6ef3'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', 'G0181', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for G0181. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08'),
  ('b560cbad-eb31-42e4-89e2-753499a250ef'::uuid, 'a0000000-0000-4000-8000-000000000301'::uuid, 'OH', 'commercial', 'G0318', 'frequency_limit', '{"answer":"Aetna publishes no frequency or visit limit for G0318. Its Clinical Policy Bulletin notes state that each benefit plan defines which services are covered, which are excluded, \"and which are subject to dollar caps or other limits\" — so any limit on this code lives in the member''s specific benefit document, not in a schedule Aetna publishes per code. Check the member''s plan documents or Aetna''s eligibility and benefits response before billing repeat visits; do not assume there is no cap because none is published here. This is recorded as unestablished rather than unlimited: Aetna says a limit may exist, only not where it can be read per code.","source":"Aetna — Clinical Policy Bulletin Notes, retrieved 2026-08-13","appliesToService":"limits defined by the individual benefit plan"}'::jsonb, 'unknown', 0.7, DATE '2026-01-01', NULL, 'f2000000-0001-4000-8000-00000000b001'::uuid, 'Each benefit plan defines which services are covered, which are excluded, and which are subject to dollar caps or other limits.', 'extract:aetna-frequency-basis-2026-08')
ON CONFLICT (id) DO UPDATE SET
  value = EXCLUDED.value, coverage_status = EXCLUDED.coverage_status,
  product_line = EXCLUDED.product_line, confidence = EXCLUDED.confidence,
  source_quote = EXCLUDED.source_quote, effective_date = EXCLUDED.effective_date,
  expiration_date = NULL, source_doc_id = EXCLUDED.source_doc_id;

COMMIT;
